apiVersion: batch/v1
kind: Job
metadata:
  name: soilnet-zipvis
spec:
  template:
    spec:
      priorityClassName: research-low
      containers:
        - name: soilnet-docker
          image: lsx-staff-registry.informatik.uni-wuerzburg.de/dulny/soilnet-feb2022:latest
          workingDir: /home/ls6/dulny/soilnet-Feb2022/
          imagePullPolicy: "Always"
          env:
            - name: LOGNAME
              value: "dulny"
            - name: USER
              value: "dulny"
            - name: OMP_NUM_THREADS
              value: "4"
          resources:
            limits:
              cpu: "4"
              memory: "32Gi"
            requests:
              cpu: "4"
              memory: "32Gi"
          command: ["python3", "-u", "zip_vingilot.py"]
          args: []
          volumeMounts:
            - mountPath: "/home/ls6/dulny/soilnet-Feb2022/dataset/data/"
              name: data
            - mountPath: "/home/ls6/dulny/soilnet-Feb2022/results"
              name: output
      imagePullSecrets:
        - name: lsx-staff-registry
      restartPolicy: "Never"
      volumes:
        - name: data
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: dulny  # <namespace>
            path: "/home/ls6/dulny/soilnet-Feb2022/dataset/data/" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret
        - name: output
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: dulny  # <namespace>
            path: "/home/ls6/dulny/soilnet-Feb2022/results" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret
