name: 'vargp'
parameters:
  kernel:
    name: 'matern'
    parameters:
      nu: 2.5
  num_tasks: 3
  num_latents: 2
  num_inducing_points: 128
  learning_rate: 0.006467240892240539
  val_metric: mse
  n_epochs: 100
