defaults:
  - model: soilcnn
  - vars: full
  - model@weak_model: rf
  - patch: make_patch

dataset:
  path_labeled: dataset/data/Feb_2022/uf_lab.csv
  path_unlabeled: dataset/data/Feb_2022/uf_unlab.csv
  n_splits: 10
  random_seed: 4212

general:
  verbose: true
  save_predictions: false

hydra:
  sweep:
    dir: mulitrun_search/${hydra.sweeper.study_name}/${now:%Y-%m-%d--%H-%M-%S}
    subdir: ${hydra.job.num}
